### PR TITLE
Added a package-creator for Debian (issue #73).

### PR DESCRIPTION
**Pull request by nerun**
## As per issue #73:
* removed very old debian package files
* added script to automaticaly create a `.deb` package
## Usage:
First you should compile source, then execute script.
```
cd linapple
make
cd pkg
./package-creator
```
## More info
Script keeps things clean, it removes everything inside `linapple/pkg` after executed, except the new created debian package and script itself.

All files are installed by default in `/usr/local` as does `make install`.

It's a very basic package:
* DEBIAN/conffiles
* DEBIAN/control
* DEBIAN/md5sums
* usr/local/bin
* usr/local/etc/linapple/linapple.conf
* usr/local/share/linapple/Master.dsk

### CODE REVIEW

**Comment by maxolasersquad** [comment]
Two questions.

1. Could this be made a MAKE recipe?
2. Should this be made a MAKE recipe?

**Comment by nerun** [comment]
> 1. Could this be made a MAKE recipe?

If yes, i don't know how.

> 2. Should this be made a MAKE recipe?

I think not, i believe it's better the way it is. That `/pkg` was always there, apparently never used. Anyway, this PR is better than the current contents of the `/pkg` directory, and the script is quite useful. It's like an upgrade/update.

**Comment by nerun** [comment]
Hey, I just noticed package creation inside makefile. I will study this a little more.

**Comment by nerun** [comment]
Ha! I know what to do now!

**Comment by maxolasersquad** [comment]
Beauty.

**Pull request merged**
