### PR TITLE
Remove commented-out code, unnecessary comments, and other cruft

### PR DESCRIPTION
**Pull request by maxolasersquad**

### CODE REVIEW

**Comment by maxolasersquad** [comment]
This is another step in the quest of overhaul the code for future development. This has A LOT of changes in it. I have verified it builds and runs, but not much else beyond that. Before being approved it really should be looked over by at least one other person, especially someone with more C and C++ experience.

**Comment by ghedger** [comment]
Looking at it..

**Comment by maxolasersquad** [comment]
I played about 5 minutes of Conan and had no issues, FWIW.

**Comment by ghedger** [comment]
I checked Skyfox (uses extended 16k, Mockingboard), AutoDuel (joystick), and my own game-in-progress Achterlanden (double-hires, Mockingboard, extended 16k, and auxillary RAM); no issues.

**Comment by ghedger** [comment]
Merged.  Good work.

**Pull request merged**
