### PR TITLE
Documentation Cleanup

### PR DESCRIPTION
**Pull request by 0cjs**
This is a start on some documentation cleanup and correction. See the commit messages for details.

### CODE REVIEW

**Comment by maxolasersquad** [comment]
This now conflicts because of the last MR.

**Comment by 0cjs** [comment]
> This now conflicts because of the last MR.

I'm always happy to rebase my work against a new `master`! This is now all fixed up, though I don't know why the second Travis job is still not finished after more than two and a half hours.

**Comment by maxolasersquad** [comment]
Given that there are 0 code changes I think we can safely merge before the job finishes.

**Comment by 0cjs** [comment]
I pushed up a new version of this branch a couple of days ago to make the commits a bit clearer (extracting a fix buried in a commit to a new commit at the start), and it all seems to have passed now. So unless there are other issues to discuss about it, it's ready to go on to `master`.

**Comment by maxolasersquad** [comment]
My apologies. I thought I had clicked the merge button at my last comment.

**Comment by 0cjs** [comment]
No problem; thanks for the merge!

**Pull request merged**
