### PR TITLE
Eject support

### PR DESCRIPTION
**Pull request by lowlevel-1989**
Thanks [timriker](https://github.com/timriker) #190 

++1. Update Readme.
++2. Eject  floppy or harddrive.
++3. Update Registry for support save config in runtime. (optional) from **make -e REGISTRY_WRITEABLE=1**

~~~text
| -------------- | -----------------------------------------------------------------|
| F3             | Load disk image to slot 6 drive 1.                               |
| F4             | Load disk image to slot 6 drive 2.                               |
| F5             | Swap drives for slot 6.                                          |
| Alt+F3         | Load disk image to slot 6 drive 1 from FTP server.               |
| Alt+F4         | Load disk image to slot 6 drive 2 from FTP server.               |
| Shift+F3       | Attach hard disk image to slot 7 drive 1.                        |
| Shift+F4       | Attach hard disk image to slot 7 drive 2.                        |
| Alt+Shift+F3   | Attach hard disk image to slot 7 from FTP server.                |
| Alt+Shift+F4   | Attach hard disk image to slot 7 from FTP server.                |
| Ctrl+F3        | Eject disk image to slot 6 drive 1.                              |
| Ctrl+F4        | Eject disk image to slot 6 drive 2.                              |
| Ctrl+Shift+F3  | Eject hard disk image to slot 7 drive 1.                         |
| Ctrl+Shift+F4  | Eject hard disk image to slot 7 drive 2.                         |
| -------------- | -----------------------------------------------------------------|
~~~

### CODE REVIEW

**Comment by maxolasersquad** [comment]
This looks good to me.

@timriker, are you able to give this a compile, to see if you have any feedback on the implementation?

@ghedger, do you have any feedback on this?

**Comment by ghedger** [comment]
I think if the help screen reflects the new key mappings it should be fine.

Am I correct in understanding "F5- Swap drives for slot 6" to mean drive 2 and its disk becomes drive 1 and vice versa?  That seems to be the plain meaning.

And the meaning of eject -- this is basically an unmount of the HD image?

Good work, and looks like it's all right.

**Comment by lowlevel-1989** [comment]
> I think if the help screen reflects the new key mappings it should be fine.
> 
> Am I correct in understanding "F5- Swap drives for slot 6" to mean drive 2 and its disk becomes drive 1 and vice versa? That seems to be the plain meaning.
> 
> And the meaning of eject -- this is basically an unmount of the HD image?
> 
> Good work, and looks like it's all right.
that's correct, thank you very much. 

On the other hand, in another pull request #192 , I have also added support for Spanish keyboard and simple compilation in fedora so that it behaves the same as the compilation in debian.

**Comment by lowlevel-1989** [comment]
>

**Comment by timriker** [comment]
I have not yet compiled this. I'll do that soon.

If the disk select screen had an eject button, then no more key shortcuts would be required. It would be nice if there was a master menu that could navigate with a joystick to the other menus. I could see selecting an image even from an ftp site with just a joystick.

**Comment by timriker** [comment]
The REGISTRY_WRITEABLE changes are only half in this pull request. It won't let me change disks.

**Comment by lowlevel-1989** [comment]
> The REGISTRY_WRITEABLE changes are only half

I do not understand what you mean, could you explain me a little better if you are presenting a problem?

**Comment by timriker** [comment]
Tested on my WSL Ubuntu 22.04 install. It can't find an DSL audio and the boot hangs. I had set:
PULSE_SERVER=tcp:172.17.112.1
but pulseaudio was not running on Windows. Starting it boots up fine.
Once I have pulse audio working, it boots as expected and I get logs like:

Disk Eject Drive #1
update conf = /home/timr/.config/linapple/linapple.conf

It might make more sense to add an <eject disk> before the ".." or some other way of integrating into the F3/F4 shift, alt, menus. Perhaps a key that works only there? <enter> chooses, <esc> exits the menu. We could add <space> to eject? and <eject> before the .. could allow navigating with a joystick.

**Comment by ghedger** [comment]
> It might make more sense to add an before the ".." or some other way of integrating into the F3/F4 shift, alt, menus. Perhaps a key that works only there? chooses, exits the menu. We could add to eject? and before the .. could allow navigating with a joystick.

That menu needs a ton of work, as in a total refactor.  It has issues with large numbers of items and scrolling.  There are hardcoded pixel values for character sizes and text rendering placement.  It's nice that it uses the Apple II character set, but I think it's not scaled properly -- or in some forks it was, in some it wasn't, something like that.   I had added a way to jump to the first item starting with a letter pressed for navigation, but the disk select interface needs gutting and a total remodel.    I haven't looked at this project in over a year (been busy) but this has been at the back of my mind.

**Comment by lowlevel-1989** [comment]
> 

Indeed it is as you comment, creating a new menu system would be a feature that could be developed in the future, since it is a job of rewriting the system and making it more modular.

For my part, the main feature of this request is correct and working, I am currently working on giving full support to Spanish and making linapple work in a stable way both in linux and in retropie (rpi) and I could not spend time on a new system menu at the moment.

**Comment by lowlevel-1989** [comment]
@maxolasersquad Do you agree? pull request, ok?

**Pull request merged**
