### PR TITLE
Allow relative paths in command-line options.

### PR DESCRIPTION
**Pull request by cpressey**
When testing autoboot I initially thought it had been broken by recent changes. But eventually I noticed that I was using a relative path to my disk to the `-d1` option, and that the documentation says that you should use the full path. Doing that fixed the problem. Autoboot was not broken...

However, seeing no theoretical reason for the full-path requirement, I looked into why it needed that. It turns out that it needs that because linapple changes directory to the `$HOME/linapple` directory after starting. However, the only reason it does that is so that it can find the `linapple.conf` file in the current directory.

Since at this point that is the *only* file that it expects to be in the current directory, and since it is entirely possible to locate that file by prepending the user dir to it instead, that's what this change does.

And that, in turn, lets us say `-d1 example.dsk` on the command-line, and having that act as you would expect it to act, i.e. it looks for `example.dsk` in the current directory, and inserts it.

And since that works now, I updated the notes about command-line options in the README, and since those note repeat and supercede Command-line.md, I deleted that old file.

### CODE REVIEW

**Comment by maxolasersquad** [comment]
These changes look good to me. I'll leave it up to @iKarith to review and merge in if he concurs.

**Comment by maxolasersquad** [comment]
@cpressey Would you please review my merge conflict resolution commit?

**Comment by rhaleblian** [comment]
I feel that any `clang-format` changes i've done should not be taken until this PR* goes in.


* this really goes for all of the outstanding PRs.

**Comment by cpressey** [comment]
@maxolasersquad Sorry, missed your comment at the time. https://github.com/linappleii/linapple/pull/26/commits/736343613c343a37a910099cac4a21a730060fe6 looks fine to me.

**Comment by rhaleblian** [comment]
When this goes in i'll rebase atop it.

**Pull request merged**
