### PR TITLE
#45 Add joystick configuration from @dabonetn .

### PR DESCRIPTION
**Pull request by rhaleblian**
This is, like the BMP embedding changes, taken from @dabonetn 's fork.
It adds joystick axis and button mapping, and ability to exit the emulator with a 2 button chord.

### CODE REVIEW

**Comment by dabonetn** [comment]
Thanks! I'm looking forward to seeing where this goes.

**Comment by rhaleblian** [comment]
Sure @dabonetn , thanks for swinging by.

**Comment by rhaleblian** [comment]
One thing: the config example implies that buttons are counted from 1 but all else is counted from 0. If so, would be good to count buttons from 0 too.
This would break RetroPie users unless we read, altered and wrote new keys (by inference), and wrote a key into the config denoting we upgraded it, so we don't keep upgrading it. That key could be "Configuration Version", say.

**Comment by rhaleblian** [comment]
To test this, pull it and incorporate the additional Joystick conf keys into your conf.

**Comment by rhaleblian** [comment]
I request that this get merged despite my comment regarding 0-or-1 button identifiers, to get parity first.

**Pull request merged**
